src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $order_uid;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $shipping_status;

    /**
     * @ORM\Column(type="float")
     */
    private $shipping_price;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $shipping_payment_status;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $payment_status;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $currency;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="float")
     */
    private $order_amount;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $orderItems = [];

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="order", orphanRemoval=true,cascade={"persist"})
     */
    private $order_items;

    public function __construct()
    {
        $this->order_items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderUid(): ?string
    {
        return $this->order_uid;
    }

    public function setOrderUid(string $order_uid): self
    {
        $this->order_uid = $order_uid;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone = null): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getShippingStatus(): ?string
    {
        return $this->shipping_status;
    }

    public function setShippingStatus(string $shipping_status): self
    {
        $this->shipping_status = $shipping_status;

        return $this;
    }

    public function getShippingPrice(): ?float
    {
        return $this->shipping_price;
    }

    public function setShippingPrice(float $shipping_price): self
    {
        $this->shipping_price = $shipping_price;

        return $this;
    }

    public function getShippingPaymentStatus(): ?string
    {
        return $this->shipping_payment_status;
    }

    public function setShippingPaymentStatus(string $shipping_payment_status): self
    {
        $this->shipping_payment_status = $shipping_payment_status;

        return $this;
    }

    public function getPaymentStatus(): ?string
    {
        return $this->payment_status;
    }

    public function setPaymentStatus(string $payment_status): self
    {
        $this->payment_status = $payment_status;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getOrderItems(): ?Collection
    {
        return $this->order_items;
    }

    public function setOrderItems(?array $orderItems): self
    {
        $this->orderItems = $orderItems;

        return $this;
    }

    public function getOrderAmount(): ?float
    {
        return $this->order_amount;
    }

    public function setOrderAmount(float $orderAmount): self
    {
        $this->order_amount = $orderAmount;

        return $this;
    }

    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->order_items->contains($orderItem)) {
            $this->order_items[] = $orderItem;
            $orderItem->setOrder($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->order_items->contains($orderItem)) {
            $this->order_items->removeElement($orderItem);
            // set the owning side to null (unless already changed)
            if ($orderItem->getOrder() === $this) {
                $orderItem->setOrder(null);
            }
        }

        return $this;
    }
}

src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;

use App\Entity\Order;

/**
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="order_items", fetch="EAGER",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $order;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $order_uid;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $barcode;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $tax_perc;

    /**
     * @ORM\Column(type="float")
     */
    private $tax_amt;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $tracking_number;

    /**
     * @ORM\Column(type="boolean")
     */
    private $canceled;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $shipped_status_sku;

    public function getId(): ?int
    {
        return $this->id;
    }

    //public function getOrder(): ?Order
    //{
    //    return $this->order;
    //}

    public function setOrder(Order $orderId): self
    {
        $this->order = $orderId;

        return $this;
    }

    public function getOrderUid(): ?string
    {
        return $this->order_uid;
    }

    public function setOrderUid(string $orderUid): self
    {
        $this->order_uid = $orderUid;

        return $this;
    }

    public function getBarcode(): ?string
    {
        return $this->barcode;
    }

    public function setBarcode(string $barcode): self
    {
        $this->barcode = $barcode;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTaxPerc(): ?float
    {
        return $this->tax_perc;
    }

    public function setTaxPerc(float $tax_perc): self
    {
        $this->tax_perc = $tax_perc;

        return $this;
    }

    public function getTaxAmt(): ?float
    {
        return $this->tax_amt;
    }

    public function setTaxAmt(float $tax_amt): self
    {
        $this->tax_amt = $tax_amt;

        return $this;
    }

    public function getTrackingNumber(): ?string
    {
        return $this->tracking_number;
    }

    public function setTrackingNumber(?string $tracking_number): self
    {
        $this->tracking_number = $tracking_number;

        return $this;
    }

    public function getCanceled(): ?bool
    {
        return $this->canceled;
    }

    public function setCanceled(bool $canceled): self
    {
        $this->canceled = $canceled;

        return $this;
    }

    public function getShippedStatusSku(): ?string
    {
        return $this->shipped_status_sku;
    }

    public function setShippedStatusSku(string $shipped_status_sku): self
    {
        $this->shipped_status_sku = $shipped_status_sku;

        return $this;
    }
}

src/Controller/Api/v1/OrderController.php
<?php

namespace App\Controller\Api\v1;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use App\Service\OrderService;
use App\Service\SyncOrderFromUnkownApiService;


class OrderController extends AbstractController
{
    private $orderService;
    private $syncOrdersService;

    public function __construct(OrderService $orderService, SyncOrderFromUnkownApiService $syncOrdersService)
    {
        $this->orderService = $orderService;
        $this->syncOrdersService = $syncOrdersService;
    }
	
    /**
     * @Route("/api/v1/orders", name="api_orders")
     */
    public function index(): Response
    {
        return $this->json($this->orderService->findAllWithOrderItems());
    }
	
    /**
     * @Route("/api/v1/order/{id}", name="api_show_order")
     */
    public function show(Request $request, $id): Response
    {
        return $this->json($this->orderService->find($id));
    }
	
    /**
     * @Route("/api/v1/sync_orders", name="api_sync_orders")
     */
    public function sync(): Response
    {
        return $this->json($this->syncOrdersService->doSyncOrders());
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use App\Service\OrderService;
use App\Service\SyncOrderFromUnkownApiService;


class OrderController extends AbstractController
{
    private $orderService;
    private $syncOrdersService;

    public function __construct(OrderService $orderService, SyncOrderFromUnkownApiService $syncOrdersService)
    {
        $this->orderService = $orderService;
        $this->syncOrdersService = $syncOrdersService;
    }
	
    /**
     * @Route("/order", name="orders")
     */
    public function index()
    {
        return $this->render('order/index.html.twig', [
            'orders' => $this->orderService->findAll(),
        ]);
    }
	
    /**
     * @Route("/order/{id}", name="show_order")
     */
    public function show(Request $request, $id)
    {
        return $this->render('order/show.html.twig', [
			'order' => $this->orderService->findOneWithOrderItems($id)
        ]);
    }
	
    /**
     * @Route("/sync_orders", name="sync_orders")
     */
    public function sync()
    {
        return $this->render('order/sync.html.twig', [
            'orders' => $this->syncOrdersService->doSyncOrders(),
        ]);
    }
}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}
{% block h_one %}Orders{% endblock %}

{% block body %}
<table class="table">
	<thead>
		<tr>
			<th scope="col">Id</th>
			<th scope="col">Order ID</th>
			<th scope="col">Date</th>
			<th scope="col">Amount</th>
			<th scope="col"></th>
		</tr>
	</thead>
	<tbody>
		{% for order in orders %}
			<tr class="align-middle">
				<td class="align-middle">{{ order.id }}</td>
				<td class="align-middle">{{ order.orderUid }}</td>
				<td class="align-middle">{{ order.date|date }}</td>
				<td class="align-baseline">{{ order.orderAmount }} {{ order.currency }}</td>
				<td><a class="btn btn-sm btn-info" href="{{ path('show_order', {id: order.id}) }}">Details</a></td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order {{ order.orderUid }} Details{% endblock %}
{% block h_one %}Order {{ order.orderUid }} Details{% endblock %}

{% block body %}
<div class="row">
	<div class="col-3 text-right font-weight-bold">Order ID:</div>
	<div class="col-9">{{ order.orderUid }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Phone:</div>
	<div class="col-9"><a href="tel:{{ order.phone }}">{{ order.phone }}</a></div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Date:</div>
	<div class="col-9">{{ order.date|date }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Amount:</div>
	<div class="col-9">{{ order.orderAmount }} {{ order.currency }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Currency:</div>
	<div class="col-9">{{ order.currency }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Shipping Status:</div>
	<div class="col-9">{{ order.shippingStatus }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Shipping Price:</div>
	<div class="col-9">{{ order.shippingPrice }} {{ order.currency }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Shipping Payment Status:</div>
	<div class="col-9">{{ order.shippingPaymentStatus }}</div>
</div>
<div class="row">
	<div class="col-3 text-right font-weight-bold">Payment Status:</div>
	<div class="col-9">{{ order.paymentStatus }}</div>
</div>

<h3 class="mt-2 mb-2">Order Items:</h3> 

<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th class="col">Barcode</th>
				<th class="col">Price</th>
				<th class="col">Quantity</th>
				<th class="col">Tax Perc</th>
				<th class="col">Tax Amt</th>
				<th class="col">Tracking Number</th>
				<th class="col">Canceled</th>
				<th class="col w-100">Shipped Status Sku</th>
			</tr>
		</thead>
		{% for item in order.orderItems %}
			<tr>
				<td style="width: 10em" class="col">{{ item.barcode }}</td>
				<td class="col">{{ item.price }}</td>
				<td class="col">{{ item.quantity }}</td>
				<td class="col">{{ item.taxPerc }}</td>
				<td class="col">{{ item.taxAmt }}</td>
				<td class="col">{{ item.trackingNumber }}</td>
				<td class="col">{{ item.canceled }}</td>
				<td class="col">{{ item.shippedStatusSku }}</td>
			</tr>
		{% endfor %}
	</table>
</div>

</div>
{% endblock %}

templates/order/sync.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sync Details{% endblock %}
{% block h_one %}Sync Details{% endblock %}

{% block body %}
<b>Gotten Orders:</b> {{ orders|length }}


</div>
{% endblock %}